### ISSUE TITLE
MS COCO Caption scores with MLE objective

### ISSUE THREAD

**Issue by j-min** [clip-vil/CLIP-ViL#1]
Hi, thanks for sharing your code! This is a very interesting work :)
Could you please let me know the MS COCO scores on the Karpathy test split with MLE objectives only (before self-critical learning)?

**Comment by sIncerass** [comment]
Hi, thanks for your interest!
Yeah, before self-critical you can just use the configs located at [phrase1](https://github.com/clip-vil/CLIP-ViL/tree/master/CLIP-ViL-Direct/caption/configs/phrase1) following the scripts we described in the README file.
