### ISSUE TITLE
configuration file for CLIP-Res50x4

### ISSUE THREAD

**Issue by itsyoavshalev** [clip-vil/CLIP-ViL#10]
Hi, two small questions,
1. I see that there is a configuration file for CLIP-Res50, but not for CLIP-Res50x4 (CLIP-ViL/CLIP-ViL-Direct/vqa/configs/).
Can you upload the file?

2. In addition, for how many epochs you fine tuned CLIP-Res50x4/pythia/vqa2 ?
It's not mentioned in the paper.

Thanks for your help.

**Comment by sIncerass** [comment]
Hi there, sorry for the late reply. I just update the config [here](https://github.com/clip-vil/CLIP-ViL/blob/master/CLIP-ViL-Direct/vqa/mmf_configs/pythia/local_clip_rn50x4.yaml). We use the default config for pythia finetuning, which is in total 22000 number of steps. 
```
progress: 22000/22000, val/vqa2/logit_bce: xxxx, val/total_loss: xxxx val/
vqa2/vqa_accuracy: 0.xxx, num_updates: 22000, epoch: 26, iterations: 22000, max_updates: 22000, val_time: 04m 43s 513ms, best_update:
xxx, best_iteration: xxx, best_val/vqa2/vqa_accuracy: 0.xxx
```
