### ISSUE TITLE
Missed Link

### ISSUE THREAD

**Issue by jdiazram** [clip-vil/CLIP-ViL#11]
In the readme.md (https://github.com/clip-vil/CLIP-ViL/tree/master/CLIP-ViL-VLN) there is a text: "_The images (skyboxes) need to be downloaded from [here] to extract the features_." but the link about [here] does not exit. Can you provide this file o link?

Thank you

**Comment by airsplay** [comment]
Sure, here is the link: https://niessner.github.io/Matterport/. You need to submit an agreement form to  Matterport3d team and they would provide you with the script to download skyboxes.
