### ISSUE TITLE
bug in positional_embedding's weights when resizing. 

### ISSUE THREAD

**Issue by jianjieluo** [clip-vil/CLIP-ViL#13]
Hi, @airsplay , @sIncerass , @liunian-harold-li , @clip-vil 

Thanks for sharing your code! This is a very interesting work :)

However, I find that there may be an inappropriate operation in `./CLIP-ViL-Direct/caption/scripts/clip_prepro_feats.py` when extracting the visual CLIP features. Specifically, when you [resize the official CLIP models' `positional_embedding`](https://github.com/clip-vil/CLIP-ViL/blob/3f2d2a03e604d67cc5f3e8812e023bd08f024b88/CLIP-ViL-Direct/caption/scripts/clip_prepro_feats.py#L82) to support larger image input resolution than the official CLIP models, you assign `pos_embed.weight` with the resized pos_embed weights while the `pos_embed.data` actually used in `forward()` remains zeros. I guess the **lack of positional_embedding's weights when extracting the CLIP grid features is the true reason for the large performance degradation on the experiments using CLIP-ViT-B grid features**. The performances on CLIP ResNet models are relatively normal because the `model.visual.attnpool.positional_embedding` layer is only used on the top of CLIP ResNet models to aggregate the extracted grid features for the global visual feature.

To verify my guess, I re-implement a new [feature-extraction pipeline](https://github.com/jianjieluo/OpenAI-CLIP-Feature) and run the COCO Captioning task using [X-modaler](https://github.com/YehLi/xmodaler) codebase with the extracted CLIP grid features. I get **127.8** CIDEr score using `ViT-B/32_448` CLIP grid features. I have provided my detailed experiment results on COCO Captioning [here](https://github.com/jianjieluo/OpenAI-CLIP-Feature).

So I wonder whether the lack of positional_embedding's weights when extracting CLIP-ViT-B grid features also destroyed the performance on VQA tasks? And the visualization and conclusion in Figure3 will change after providing the pos_embed_weights when extracting CLIP-ViT-B grid features?

Best,
Jianjie

**Comment by jianjieluo** [comment]
I have made a pull request #14 which makes minimal changes to fix the resize_pos_embed bug when extracting CLIP visual features. You can also use my re-implemented new [OpenAI-CLIP-Feature extraction pipeline](https://github.com/jianjieluo/OpenAI-CLIP-Feature) which encapsulates minor-modified CLIP code in order to extract not only global visual features but also local grid visual features from different CLIP visual models.



Best,
Jianjie

**Comment by sIncerass** [comment]
Hi @jianjieluo, thanks for pointing out that bug in the uploaded codebase! I will merge that into our codebase and update the results. That could potentially affect the direct caption results, but will not affect the visualization in figure 3 given the resize function will not be used there.
