### ISSUE TITLE
Train with a single GPU

### ISSUE THREAD

**Issue by ruinianxu** [clip-vil/CLIP-ViL#16]
Hi Sheng,

I wonder if the training script works for single GPU. I am facing this issue RuntimeErrorRuntimeError: : cuda runtime error (101) : invalid device ordinal and searched it might be related to the requirement of multiple GPUs.

Best,
Ruinian Xu

**Comment by sIncerass** [comment]
Hi @ruinianxu, which task are you trying to run? The caption code should work for a single GPU.
