### ISSUE TITLE
The links to download CLIP features on the R2R/RxR environment are invalid.

### ISSUE THREAD

**Issue by chenguanqi** [clip-vil/CLIP-ViL#17]
Hi, 

The given links to download CLIP features on the R2R/RxR environment are invalid now. Could you provide some new links? 

Thank you in advance!

**Comment by airsplay** [comment]
We can still access the links on our end. Can you try whether the following link is reachable in your browser: [https://nlp.cs.unc.edu/data/vln_clip/features/](https://nlp.cs.unc.edu/data/vln_clip/features/)?

**Comment by chenguanqi** [comment]
Thank you! The problem has been solved.
