### ISSUE TITLE
The extracted feature of the COCO dataset for caption

### ISSUE THREAD

**Issue by liujiaheng** [clip-vil/CLIP-ViL#18]
![image](https://user-images.githubusercontent.com/27964642/148646140-b0a7578a-f06d-42e0-b536-a7d4120dfcf3.png)
In CLIP-ViL/CLIP-ViL-Direct/caption/clip.py,         "x = x + self.positional_embedding[0, :, None, :].to(x.dtype)  # (HW+1)NC"
should be  " x = x + self.positional_embedding[:, None, :].to(x.dtype)  # (HW+1)NC"

Could you explain why you change the following code of the official clip?
In official clip,  out_proj_weight=self.c_proj.weight, out_proj_bias=self.c_proj.bias.
In your code,
![image](https://user-images.githubusercontent.com/27964642/148646205-042d401d-d7e2-411d-af07-e76f1d73ada7.png)

**Comment by Timon0327** [comment]
@liujiaheng I have the same problem when I modified the original code to "x = x + self.positional_embedding[:, None, :]", the output of the multihead self-attention turned to be same values. have experienced the "same values" problem？

**Comment by sIncerass** [comment]
Hi @liujiaheng, thanks for pointing this out. That's some inconsistent coding in our preliminary exploration. We just fix that to be consistent with the official repo.

**Comment by Timon0327** [comment]
Hi,


Thanks for your modify. But when I apply for new modified codes, the model.encode(image) just has one output that shape is (1,2048), I suppose that this feature just tmp_fc. Could you check it, please? And there is another problem for me , when I run the eval.py, the shape of model is (512, 2560), but the feature should be (1, 2048), I think it is strange. Could you help me, please?


Many thanks and best wishes,


Peng













At 2022-01-13 14:32:26, "Sheng Shen" ***@***.***> wrote:

Hi @liujiaheng, thanks for pointing this out. That's some inconsistent coding in our preliminary exploration. We just fix that to be consistent with the official repo.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sIncerass** [comment]
Hi @Timon0327, that is due to CLIP official repo's encode(image) will only give you one vector for the whole image, u can refer to the code here about how to get the tmp_att [https://github.com/clip-vil/CLIP-ViL/blob/cb8b011b9ef26a2e29a9f6ef35599ea725b6b9f0/CLIP-ViL-Direct/caption/scripts/clip_prepro_feats.py#L118-L132](https://github.com/clip-vil/CLIP-ViL/blob/cb8b011b9ef26a2e29a9f6ef35599ea725b6b9f0/CLIP-ViL-Direct/caption/scripts/clip_prepro_feats.py#L118-L132).
