### ISSUE TITLE
Errors occurred when extracting clip features using ViT-B/32

### ISSUE THREAD

**Issue by tianjunyu0871** [clip-vil/CLIP-ViL#21]
Thanks for sharing your code!
When I run clip_prepro_feats.py, the following error occurred. I tried many times, but still failed. I hope to get your help. 

<img width="730" alt="捕获" src="https://user-images.githubusercontent.com/55222964/151110813-b90c5f3e-ce53-47d4-8c82-5fbcada5d639.PNG">

**Comment by sIncerass** [comment]
Hi @tianjunyu0871, thanks for asking!
It is some version control bug we had. I just fixed it [here](https://github.com/clip-vil/CLIP-ViL/blob/8c3acc31440268383baf67d1a72c008b9cf91f70/CLIP-ViL-Direct/caption/scripts/clip_prepro_feats.py#L82-L87).
