### ISSUE TITLE
Errors occurred when extracting clip features using Resnet

### ISSUE THREAD

**Issue by tianjunyu0871** [clip-vil/CLIP-ViL#22]
Thank you for your answer to the previous question.
The following errors occurred when I used resnet model to extract clip features. The dimension of x is 3, the dimension of self.positional_embedding is 2, but the dimension of slice operation is 4. I don't know what was wrong and I hope to get your help. Thank you very much.
![QQ图片20220127100529](https://user-images.githubusercontent.com/55222964/151278847-e7ec56f3-1dee-4d9c-8e33-a8e59a6fcc9c.png)

**Comment by sIncerass** [comment]
Hi @tianjunyu0871, this was fixed as well.
