### ISSUE TITLE
error in clip extraction code: precomute_imagenet_views.py

### ISSUE THREAD

**Issue by wangqian621** [clip-vil/CLIP-ViL#23]
Error occurred while extracting clip feature by running precomute_ imagenet_ views.py
![image](https://user-images.githubusercontent.com/98006439/162598180-c42feb33-cedb-47f7-84c0-f84900aff177.png)

**Comment by airsplay** [comment]
We did not encounter this error before but make sure that you have download the HM3D  dataset through the [link](https://github.com/peteanderson80/Matterport3DSimulator#dataset-download).

**Comment by RunweiSitu** [comment]
@wangqian621 Have you found the solution? How to solve this bug?

**Comment by airsplay** [comment]
That's tricky... I did not see this error before. Could you please check the original environment setup: https://github.com/peteanderson80/Matterport3DSimulator?
