### ISSUE TITLE
Data dir for mcan_clip_grid_feature.py

### ISSUE THREAD

**Issue by Fly2flies** [clip-vil/CLIP-ViL#24]
Hello, thanks for sharing such a great code base.
If I want to extract VQAv2's COCO image features (or some other dataset) by using `mcan_clip_grid_feature.py`,
how should I prepare the data format and specify the dataset directory that the code needs ?

**Comment by shamanthak-hegde** [comment]
Hey, could you mention how you resolved this issue?
