### ISSUE TITLE
About precompute

### ISSUE THREAD

**Issue by StylesZhang** [clip-vil/CLIP-ViL#25]
Hi! @airsplay. I have used precomute_imagenet_views.py and found that the result is not consistent with the tsv file provided by https://nlp.cs.unc.edu/data/vln_clip/features/CLIP-ViT-B-32-views.tsv .
I wonder that how did you get the tsv file provided on that website? I run it with the default settings(arch=vit, LABEL=False)

**Comment by airsplay** [comment]
The CLIP lib loads model in fp16 by default, you can change it to fp32 by:
```
model = model.float()
```

**Comment by StylesZhang** [comment]
Thanks! I'll try
