### ISSUE TITLE
Pythia Feature Extraction

### ISSUE THREAD

**Issue by shamanthak-hegde** [clip-vil/CLIP-ViL#28]
I'm trying to extract image features for vqa with pythia using `python pythia_clip_grid_feature.py --config-file configs/R-50-grid.yaml --dataset coco_2015_train --model_type RN50`.
Isn't this supposed to give output as 100 object features of 2048 dimension. I'm getting varying outputs of dimensions, (1, 13, 20, 2048), (1, 15, 20, 2048) and similar ones. Could anyone point out where I'm wrong and where I need to make changes to get (100, 2048) output for an image.
And what should be the format of annotation file if I am to use VQA dataset, since that doesn't have attributes like area, segmentation, categories, etc
Thanks

**Comment by sIncerass** [comment]
Hi there,

Thanks for the interest. I think you have to specify the transform to resize the image to the same dimension like 600 * 1000, then the resulting shape will be the same. 

The annotation file of vqa is like this json file [link](https://s3.amazonaws.com/cvmlp/vqa/mscoco/vqa/v2_Annotations_Train_mscoco.zip) which is constructed by Image, Question and Answer. 

Thanks,
