### ISSUE TITLE
How to reproduce the results of experiments that are shown in Table 7

### ISSUE THREAD

**Issue by raven38** [clip-vil/CLIP-ViL#33]
Thanks for your open source code! 
I'm trying the reproduce the results of experiments in Table 7 in the ICLR paper: 'Zero-Shot Performance of CLIP in VQA'.

Would you provide code or detail information for this?

**Comment by sIncerass** [comment]
Hi @raven38, thanks for your interest! We just append each label used in VQAv2 to question as [Question] + [Label] for each question and compute the most similar label with the [image] embedding of the question to compute the zero-shot performance of CLIP.
