### ISSUE TITLE
How to combine CLIP with Oscacr(or VinVL)?

### ISSUE THREAD

**Issue by 594422814** [clip-vil/CLIP-ViL#4]
Thanks for sharing the code! This is an interesting work!
I wonder how to use CLIP as the visual encoder for the pre-training models using object detection tags (such as Oscar and VinVL)?

**Comment by sIncerass** [comment]
I guess the easiest way is to replace the visual encoder's initialization of Oscar/VinVL with the CLIP and re-do the corresponding pre-training, but you might need to be careful enough since we have some negative results when directly employing CLIP for object detection tasks.
