### ISSUE TITLE
About clip feature extraction

### ISSUE THREAD

**Issue by LittleDonkey1203** [clip-vil/CLIP-ViL#5]
I found that I totally cannot get the same feature result that you provided called cocotalk att and FC feature maps. I also try to use CLIP original code to extract the result, but it's still different.
How can I solve this problem?

**Comment by sIncerass** [comment]
Hi there, could you share with me the code you are using to extract the feature result? The provided feature maps are not using CLIP to extract but to make it compatible for training with the corresponding scripts.
