### ISSUE TITLE
Pretrained weights for image captioning

### ISSUE THREAD

**Issue by zhuang93** [clip-vil/CLIP-ViL#6]
Could you provide the pretrained weights for image captioning work?

**Comment by sIncerass** [comment]
Hi there, thanks for the interest. We put our pretrained ckeckpoints are at  [CLIP-RN50](https://drive.google.com/file/d/1QgHmpXQ6ZYYDhvCsq2b3QyIz4CPGp5UL/view?usp=sharing), [CLIP-RN101](https://drive.google.com/file/d/1cNF2u0h_mZ2Z3HUKsFKEc0USW2owMs_3/view?usp=sharing), [CLIP-RN50x4](https://drive.google.com/file/d/1q0Vhl_T344wQminWC4OkRRQtqu-Mp7SO/view?usp=sharing).
