### ISSUE TITLE
evaluating vqa using pythia

### ISSUE THREAD

**Issue by itsyoavshalev** [clip-vil/CLIP-ViL#9]
Hi, thanks for publishing the code.
It seems that I'm doing something wrong with the evaluation.

1) I generated pythia features using the following command:
python pythia_clip_grid_feature.py --config-file configs/R-50-grid.yaml --dataset coco_2014_val --model_type RN50
and a new folder (./clip/RN50/val2014) with *.pth files (e.g. 42.pth) was created.

Next, I modified local_clip_r50.yaml to point to the above-generated folder, and then I tried to evaluate using MMF with the following command:
mmf_predict config=./mmf_configs/pythia/local_clip_r50.yaml datasets=vqa2 model=pythia run_type=val

but I got the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/media/yoavs/9955ec44-7fd3-499d-8f20-40a37f20674c/CLIP-ViL/CLIP-ViL-Direct/vqa/clip/RN50/val2014/COCO_val2014_000000428399.npy'
seems that the features file names are formatted differently, and just modifying files names yielded other errors.
What am I doing wrong?

2) In addition, how do I finetune (vqa, pythia) using MMF?
mmf_run config=config=./mmf_configs/pythia/local_clip_r50.yaml datasets=vqa2 model=pythia run_type=train_val
??

Thanks.

**Comment by sIncerass** [comment]
Hi there,

Sorry, I did not mention it clearly, 
1) actually this is a misname bug for pythia and mcan extraction file there, [pythia_clip_grid_feature.py](https://github.com/clip-vil/CLIP-ViL/blob/master/CLIP-ViL-Direct/vqa/pythia_clip_grid_feature.py) now should be the file you are looking for. 

2) you can use some command like the following to do training and inference:
```
mmf_run config=projects/pythia/configs/vqa2/local_bit_rn101.yaml  run_type=train_val dataset=vqa2 model=pythia env.data_dir=/rscratch/sheng.s/clip_boi/grid-feats-vqa/mmf/ env.save_dir=./local_bitm_rn101

mmf_predict config=projects/pythia/configs/vqa2/local_bit_rn101.yaml model=pythia dataset=vqa2 run_type=test env.data_dir=/rscratch/sheng.s/clip_boi/grid-feats-vqa/mmf/ checkpoint.resume_zoo=./local_bitm_rn101/best.ckpt
```
